spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: false
  h2:
    console:
      enabled: false
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/testonly
      username: root
      password: 12345
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: true