spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    # Batch App Meta database 생성 Option
    initialize-schema: always
    job:
      enabled: true

logging:
  level:
    org:
      springframework.batch.item.database: debug
      hibernate.type.descriptor.sql.BasicBinder: TRACE
    web: trace


---

spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
      auto-commit: false
      maximum-pool-size: 10
  batch:
    job:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/testonly
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 12345
  batch:
    job:
      enabled: true