spring:

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb;MODE=MySQL
      driver-class-name: org.h2.Driver
      username: sa
      password:
      auto-commit: false

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org:
      springframework.batch.item.database: debug
      hibernate.type.descriptor.sql.BasicBinder: TRACE
    web: trace

#main2:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/default
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: default
#      password: 1234
