spring:

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      springframework.batch.item.database: debug
      hibernate.type.descriptor.sql.BasicBinder: TRACE
    web: trace
